name: Docker Build and Push

on:
  push:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push service1
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./react/my-app/Dockerfile.react  # or specify a context with a compose override
          push: true
          tags: maddmich/ccse-react:latest
      -
        name: Build and push service2
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.api
          push: true
          tags: maddmich/ccse-flask:latest